### ISSUE TITLE
Text generation needs an overhaul

### ISSUE THREAD

**Issue by danieljabailey** [yorkhackspace/ConsoleGame#13]
Things to look at:
 - Complexity of words makes game play too difficult
 - Length of words may want shortening to allow larger font on Nokia LCDs

**Comment by aquila12** [comment]
I think this is a valuable one; I think a lot of folk struggle with some.  Using less (or shorter) words per control-name, or even setting a maximum syllable count would help.

**Comment by lexbailey** [comment]
Moved to new repo
https://github.com/yorkhackspace/SpacehackServer/issues/7
