### ISSUE TITLE
change nokia font to fixed width

### ISSUE THREAD

**Issue by choffee** [yorkhackspace/ConsoleGame#16]
so the code can work out the width of the screen fro wrapping and button labels

**Comment by danieljabailey** [comment]
There is a function in the font library that is used that will tell us the width of a given string. We should have the config know the width of the LCD in pixels and then we can wrap everything correctly.

**Comment by lexbailey** [comment]
Moved to new repo
https://github.com/yorkhackspace/SpacehackClient/issues/2
