### ISSUE TITLE
add a level display

### ISSUE THREAD

**Issue by choffee** [yorkhackspace/ConsoleGame#17]

**Comment by danieljabailey** [comment]
Yes. Good idea.

**Comment by aquila12** [comment]
Certainly would be good to at least show it at the start of the round - does this get shown during the game-over sequence?

**Comment by danieljabailey** [comment]
There is currently no feedback at all about rounds. You have to count. I'm
not sure the server ever really counts either though. It just shortens its
timeouts. I could be wrong though.

**Comment by lexbailey** [comment]
Moved to new repo
https://github.com/yorkhackspace/SpacehackServer/issues/4
