### ISSUE TITLE
Start button intelligence.

### ISSUE THREAD

**Issue by danieljabailey** [yorkhackspace/ConsoleGame#18]
We need better start button handling. If somebody let's go briefly then the time starts again. It should just set it back slightly. Needs more thinking.

**Comment by danieljabailey** [comment]
This problem may be solved soon: https://github.com/danieljabailey/GameStarter

**Comment by lexbailey** [comment]
Moved to new repo
https://github.com/yorkhackspace/SpacehackServer/issues/3
