### ISSUE TITLE
Use Paho Python instead of mosquitto.py

### ISSUE THREAD

**Issue by ralight** [yorkhackspace/ConsoleGame#2]
Hi there,

mosquitto.py was donated to the Eclipse Paho project for MQTT clients. It's basically the same code base, but uses a slightly different name space for the module. It's easy to port and you should think about doing so - it is the future of the mosquitto.py code.

See http://eclipse.org/paho/ for more details on Paho, or "pip install paho-mqtt" to get the client code.

All the best with your hackspace!

Cheers,

Roger

**Comment by lexbailey** [comment]
This is mostly complete and is in the master of the new repos.
I'm going to close this issue as it will all be working soon.
I am not going to open an issue on the new repo.
