### ISSUE TITLE
Practice Round

### ISSUE THREAD

**Issue by aquila12** [yorkhackspace/ConsoleGame#20]
A lot of groups end up having two goes through spacehack - one where they fail on the first round, and then another where they actually manage through a few.  These are currently either separated by the 'game over' and 'game start' sequences (and holding the buttons again), or someone needs to forcibly restart the server process to expedite it.

We were musing around this idea, and figured that maybe just a round where there aren't any lives to track, and maybe with just two instructions each - one untimed, and one with a long timeout - just to get folk to see how it operates.  Players who are returning should find this such a simple round it would be over quickly, while new players would have a chance to pick up the mechanics.

**Comment by lexbailey** [comment]
Moved to new repo
https://github.com/yorkhackspace/SpacehackServer/issues/1
